export const SALON_DATA = [
  {
    id: 1,
    name: 'Salon Liyo',
    email: 'liyo@gmail.com',
    contactNo: '0741589674',
    city: 'Colombo',
  },
  {
    id: 2,
    name: 'Salon Glow',
    email: 'glow@gmail.com',
    contactNo: '0712345678',
    city: 'Colombo',
  },
  {
    id: 3,
    name: 'Salon Style',
    email: 'style@gmail.com',
    contactNo: '0765432198',
    city: 'Kandy',
  },
  {
    id: 4,
    name: 'Salon Beauty',
    email: 'beauty@gmail.com',
    contactNo: '0777777777',
    city: 'Galle',
  },
  {
    id: 5,
    name: 'Salon Harmony',
    email: 'harmony@gmail.com',
    contactNo: '0755555555',
    city: 'Kandy',
  },
  {
    id: 6,
    name: 'Salon Elegance',
    email: 'elegance@gmail.com',
    contactNo: '0700000000',
    city: 'Colombo',
  },
  {
    id: 7,
    name: 'Salon Chic',
    email: 'chic@gmail.com',
    contactNo: '0733333333',
    city: 'Galle',
  },
  {
    id: 8,
    name: 'Salon Trends',
    email: 'trends@gmail.com',
    contactNo: '0788888888',
    city: 'Colombo',
  },
  {
    id: 9,
    name: 'Salon Elegance',
    email: 'elegance@gmail.com',
    contactNo: '0799999999',
    city: 'Kandy',
  },
  {
    id: 10,
    name: 'Salon Vogue',
    email: 'vogue@gmail.com',
    contactNo: '0701111222',
    city: 'Galle',
  },
  {
    id: 11,
    name: 'Salon Bliss',
    email: 'bliss@gmail.com',
    contactNo: '0712345678',
    city: 'Colombo',
  },
  {
    id: 12,
    name: 'Salon Harmony',
    email: 'harmony@gmail.com',
    contactNo: '0723456789',
    city: 'Kandy',
  },
  {
    id: 13,
    name: 'Salon Glow',
    email: 'glow@gmail.com',
    contactNo: '0734567890',
    city: 'Galle',
  },
  {
    id: 14,
    name: 'Salon Radiance',
    email: 'radiance@gmail.com',
    contactNo: '0745678901',
    city: 'Colombo',
  },
  {
    id: 15,
    name: 'Salon Style',
    email: 'style@gmail.com',
    contactNo: '0756789012',
    city: 'Kandy',
  },
  {
    id: 16,
    name: 'Salon Trends',
    email: 'trends@gmail.com',
    contactNo: '0767890123',
    city: 'Galle',
  },
  {
    id: 17,
    name: 'Salon Elegance',
    email: 'elegance@gmail.com',
    contactNo: '0778901234',
    city: 'Colombo',
  },
  {
    id: 18,
    name: 'Salon Vogue',
    email: 'vogue@gmail.com',
    contactNo: '0789012345',
    city: 'Kandy',
  },
  {
    id: 19,
    name: 'Salon Bliss',
    email: 'bliss@gmail.com',
    contactNo: '0790123456',
    city: 'Galle',
  },
  {
    id: 20,
    name: 'Salon Harmony',
    email: 'harmony@gmail.com',
    contactNo: '0701234567',
    city: 'Colombo',
  },
  {
    id: 21,
    name: 'Salon Glow',
    email: 'glow@gmail.com',
    contactNo: '0712345678',
    city: 'Kandy',
  },
  {
    id: 22,
    name: 'Salon Radiance',
    email: 'radiance@gmail.com',
    contactNo: '0723456789',
    city: 'Galle',
  },
  {
    id: 23,
    name: 'Salon Style',
    email: 'style@gmail.com',
    contactNo: '0734567890',
    city: 'Colombo',
  },
  {
    id: 24,
    name: 'Salon Trends',
    email: 'trends@gmail.com',
    contactNo: '0745678901',
    city: 'Kandy',
  },
  {
    id: 25,
    name: 'Salon Elegance',
    email: 'elegance@gmail.com',
    contactNo: '0756789012',
    city: 'Galle',
  },
  {
    id: 26,
    name: 'Salon Vogue',
    email: 'vogue@gmail.com',
    contactNo: '0767890123',
    city: 'Colombo',
  },
  {
    id: 27,
    name: 'Salon Bliss',
    email: 'bliss@gmail.com',
    contactNo: '0778901234',
    city: 'Kandy',
  },
  {
    id: 28,
    name: 'Salon Harmony',
    email: 'harmony@gmail.com',
    contactNo: '0789012345',
    city: 'Galle',
  },
  {
    id: 29,
    name: 'Salon Glow',
    email: 'glow@gmail.com',
    contactNo: '0790123456',
    city: 'Colombo',
  },
  {
    id: 30,
    name: 'Salon Radiance',
    email: 'radiance@gmail.com',
    contactNo: '0701234567',
    city: 'Kandy',
  },
  {
    id: 31,
    name: 'Salon Style',
    email: 'style@gmail.com',
    contactNo: '0712345678',
    city: 'Galle',
  },
  {
    id: 32,
    name: 'Salon Trends',
    email: 'trends@gmail.com',
    contactNo: '0723456789',
    city: 'Colombo',
  },
  {
    id: 33,
    name: 'Salon Elegance',
    email: 'elegance@gmail.com',
    contactNo: '0734567890',
    city: 'Kandy',
  },
  {
    id: 34,
    name: 'Salon Vogue',
    email: 'vogue@gmail.com',
    contactNo: '0745678901',
    city: 'Galle',
  },
  {
    id: 35,
    name: 'Salon Bliss',
    email: 'bliss@gmail.com',
    contactNo: '0756789012',
    city: 'Colombo',
  },
  {
    id: 36,
    name: 'Salon Harmony',
    email: 'harmony@gmail.com',
    contactNo: '0767890123',
    city: 'Kandy',
  },
  {
    id: 37,
    name: 'Salon Beauty',
    email: 'beauty@gmail.com',
    contactNo: '0777777777',
    city: 'Galle',
  },
  {
    id: 38,
    name: 'Salon Harmony',
    email: 'harmony@gmail.com',
    contactNo: '0755555555',
    city: 'Kandy',
  },
  {
    id: 39,
    name: 'Salon Elegance',
    email: 'elegance@gmail.com',
    contactNo: '0700000000',
    city: 'Colombo',
  },
  {
    id: 40,
    name: 'Salon Chic',
    email: 'chic@gmail.com',
    contactNo: '0733333333',
    city: 'Galle',
  },
];

export const CUSTOMER_DATA = [
  {
    id: 1,
    name: 'John Doe',
    gender: 'Male',
    email: 'johndoe@gmail.com',
  },
  {
    id: 2,
    name: 'Jane Smith',
    gender: 'Female',
    email: 'janesmith@example.com',
  },
  {
    id: 3,
    name: 'Michael Johnson',
    gender: 'Male',
    email: 'michaeljohnson@example.com',
  },
  {
    id: 4,
    name: 'Emily Davis',
    gender: 'Female',
    email: 'emilydavis@example.com',
  },
  {
    id: 5,
    name: 'William Brown',
    gender: 'Male',
    email: 'williambrown@example.com',
  },
  {
    id: 6,
    name: 'Olivia Wilson',
    gender: 'Female',
    email: 'oliviawilson@example.com',
  },
  {
    id: 7,
    name: 'Daniel Martinez',
    gender: 'Male',
    email: 'danielmartinez@example.com',
  },
  {
    id: 8,
    name: 'Sophia Lee',
    gender: 'Female',
    email: 'sophialee@example.com',
  },
  {
    id: 9,
    name: 'Alexander Taylor',
    gender: 'Male',
    email: 'alexandertaylor@example.com',
  },
  {
    id: 10,
    name: 'Ava Rodriguez',
    gender: 'Female',
    email: 'avarodriguez@example.com',
  },
  {
    id: 11,
    name: 'James Clark',
    gender: 'Male',
    email: 'jamesclark@example.com',
  },
  {
    id: 12,
    name: 'Ella Hernandez',
    gender: 'Female',
    email: 'ellahernandez@example.com',
  },
  {
    id: 13,
    name: 'Benjamin Moore',
    gender: 'Male',
    email: 'benjaminmoore@example.com',
  },
  {
    id: 14,
    name: 'Mia Lewis',
    gender: 'Female',
    email: 'mialewis@example.com',
  },
  {
    id: 15,
    name: 'Ethan Hall',
    gender: 'Male',
    email: 'ethanhall@example.com',
  },
  {
    id: 16,
    name: 'John Doe',
    gender: 'Male',
    email: 'johndoe@gmail.com',
  },
  {
    id: 17,
    name: 'Jane Smith',
    gender: 'Female',
    email: 'janesmith@example.com',
  },
  {
    id: 18,
    name: 'Michael Johnson',
    gender: 'Male',
    email: 'michaeljohnson@example.com',
  },
  {
    id: 19,
    name: 'Emily Davis',
    gender: 'Female',
    email: 'emilydavis@example.com',
  },
  {
    id: 20,
    name: 'William Brown',
    gender: 'Male',
    email: 'williambrown@example.com',
  },
  {
    id: 21,
    name: 'Olivia Wilson',
    gender: 'Female',
    email: 'oliviawilson@example.com',
  },
  {
    id: 22,
    name: 'Daniel Martinez',
    gender: 'Male',
    email: 'danielmartinez@example.com',
  },
  {
    id: 23,
    name: 'Sophia Lee',
    gender: 'Female',
    email: 'sophialee@example.com',
  },
  {
    id: 24,
    name: 'Alexander Taylor',
    gender: 'Male',
    email: 'alexandertaylor@example.com',
  },
  {
    id: 25,
    name: 'Ava Rodriguez',
    gender: 'Female',
    email: 'avarodriguez@example.com',
  },
  {
    id: 26,
    name: 'James Clark',
    gender: 'Male',
    email: 'jamesclark@example.com',
  },
  {
    id: 27,
    name: 'Ella Hernandez',
    gender: 'Female',
    email: 'ellahernandez@example.com',
  },
  {
    id: 28,
    name: 'Benjamin Moore',
    gender: 'Male',
    email: 'benjaminmoore@example.com',
  },
  {
    id: 29,
    name: 'Mia Lewis',
    gender: 'Female',
    email: 'mialewis@example.com',
  },
  {
    id: 30,
    name: 'Ethan Hall',
    gender: 'Male',
    email: 'ethanhall@example.com',
  },
  {
    id: 31,
    name: 'Ava Rodriguez',
    gender: 'Female',
    email: 'avarodriguez@example.com',
  },
  {
    id: 32,
    name: 'James Clark',
    gender: 'Male',
    email: 'jamesclark@example.com',
  },
];

export const SERVICE_DATA = [
  {
    id: 1,
    name: 'Haircut',
    type: 'Hair',
    price: 500,
    duration: '30 min',
  },
  {
    id: 2,
    name: 'Hair Coloring',
    type: 'Hair',
    price: 2000,
    duration: '1 hr',
  },
  {
    id: 3,
    name: 'Hair Styling',
    type: 'Hair',
    price: 1000,
    duration: '45 min',
  },
  {
    id: 4,
    name: 'Facial',
    type: 'Skin',
    price: 1500,
    duration: '45 min',
  },
  {
    id: 5,
    name: 'Manicure',
    type: 'Nails',
    price: 800,
    duration: '30 min',
  },
  {
    id: 6,
    name: 'Pedicure',
    type: 'Nails',
    price: 1000,
    duration: '45 min',
  },
  // {
  //   id: 7,
  //   name: 'Massage',
  //   type: 'Body',
  //   price: 2000,
  //   duration: '1 hr',
  // },
  // {
  //   id: 8,
  //   name: 'Waxing',
  //   type: 'Body',
  //   price: 1500,
  //   duration: '45 min',
  // },
  // {
  //   id: 9,
  //   name: 'Threading',
  //   type: 'Face',
  //   price: 500,
  //   duration: '15 min',
  // },
  // {
  //   id: 10,
  //   name: 'Haircut',
  //   type: 'Hair',
  //   price: 500,
  //   duration: '30 min',
  // },
  // {
  //   id: 11,
  //   name: 'Hair Coloring',
  //   type: 'Hair',
  //   price: 2000,
  //   duration: '1 hr',
  // },
  // {
  //   id: 12,
  //   name: 'Hair Styling',
  //   type: 'Hair',
  //   price: 1000,
  //   duration: '45 min',
  // },
  // {
  //   id: 13,
  //   name: 'Facial',
  //   type: 'Skin',
  //   price: 1500,
  //   duration: '45 min',
  // },
];
